SELECT NOMBRE, APELLIDO, DIRECCION, CUIL
FROM PERSONA
ORDER BY APELLIDO;

SELECT NOMBRE, APELLIDO, DIRECCION, CUIL
FROM PERSONA
ORDER BY APELLIDO ASC;

SELECT TOP 5 CUIL, NOMBRE, APELLIDO, DIRECCION
FROM PERSONA
ORDER BY 2 ASC;

SELECT TOP 5 NOMBRE, APELLIDO, CUIL, DIRECCION
FROM PERSONA
ORDER BY 2 ASC;



SELECT TOP 5 CUIL, NOMBRE, APELLIDO, DIRECCION
FROM PERSONA
ORDER BY APELLIDO DESC, NOMBRE DESC;

SELECT *
FROM COMPROBANTE_CABECERA
WHERE FECHA >= '2025-01-01' AND FECHA <= '2025-01-31';

SELECT *
FROM COMPROBANTE_CABECERA
WHERE FECHA BETWEEN '2025-01-01' AND '2025-01-31';



SELECT *
FROM COMPROBANTE_DETALLE
WHERE COD_PRODUCTO IN ('LECHE', 'ARROZ', 'MATE COCIDO');

SELECT *
FROM PERSONA
WHERE NOMBRE LIKE 'AN%';  --> WHERE LEFT(NOMBRE,2) = 'AN'

SELECT *
FROM PERSONA
WHERE NOMBRE LIKE '%AN%';

SELECT *
FROM PERSONA
WHERE NOMBRE LIKE '%AN';



SELECT * FROM PERSONA WHERE 1 = 1;
SELECT * FROM PERSONA WHERE 1 <> 2;
SELECT * FROM PERSONA WHERE NULL = NULL;
SELECT * FROM PERSONA WHERE 2 = NULL;

SELECT * FROM PERSONA WHERE DOMICILIO IS NOT NULL;
SELECT * FROM PERSONA WHERE DOMICILIO IS NULL;
