CREATE TABLE dbo.EMPRESA
	(
	CUIL char(11) NOT NULL,
	RAZON_SOCIAL varchar(255) NULL,
	DIRECCION varchar(50) NOT NULL,
	TELEFONO varchar(10) NOT NULL
	)  ON [PRIMARY]
GO
ALTER TABLE dbo.EMPRESA ADD CONSTRAINT
	PK_EMPRESA PRIMARY KEY CLUSTERED 
	(
	CUIL
	) WITH( STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]

GO
ALTER TABLE dbo.EMPRESA SET (LOCK_ESCALATION = TABLE)
GO

USE [borrar]
GO

SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[Herramienta](
	[Id_Herramienta] [int] NOT NULL,
	[cuil_empresa] [char](11) NOT NULL,
	[fecha_alta] [datetime] NOT NULL,
	[razon_emp] [varchar](250) NOT NULL,
 CONSTRAINT [PK_Herramienta] PRIMARY KEY CLUSTERED 
(
	[Id_Herramienta] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO

